import type { CategoryMeta } from './types';

export const CATEGORIES: CategoryMeta[] = [
  {
    slug: 'resources',
    label: 'Resource',
    pluralLabel: 'Resources',
    description: 'Tradeable and strategic resources that power your economy.',
    defineFile: 'Resources.json',
    priority: 1,
  },
  {
    slug: 'modifiers',
    label: 'Modifier',
    pluralLabel: 'Modifiers',
    description: 'Stat modifiers applied to countries, regions, and units.',
    priority: 2,
  },
  {
    slug: 'technologies',
    label: 'Technology',
    pluralLabel: 'Technologies',
    description: 'Researchable technologies across culture, industry, and military.',
    defineFile: 'Technologies.json',
    priority: 3,
  },
  {
    slug: 'factions',
    label: 'Faction',
    pluralLabel: 'Factions',
    description: 'Political factions and their alignment effects.',
    defineFile: 'Factions.json',
    priority: 4,
  },
  {
    slug: 'faction-variants',
    label: 'Faction Variant',
    pluralLabel: 'Faction Variants',
    description: 'Variants of base factions with different modifiers.',
    defineFile: 'FactionVariants.json',
    priority: 5,
  },
  {
    slug: 'government-reforms',
    label: 'Government Reform',
    pluralLabel: 'Government Reforms',
    description: 'Government reform categories and their options.',
    defineFile: 'GovernmentReforms.json',
    priority: 6,
  },
  {
    slug: 'government-reform-options',
    label: 'Reform Option',
    pluralLabel: 'Reform Options',
    description: 'Individual government reform choices.',
    defineFile: 'GovernmentReformOptions.json',
    priority: 7,
  },
  {
    slug: 'projects',
    label: 'Project',
    pluralLabel: 'Projects',
    description: 'Buildable projects and industries.',
    defineFile: 'Projects.json',
    priority: 8,
  },
  {
    slug: 'unit-components',
    label: 'Unit Component',
    pluralLabel: 'Unit Components',
    description: 'Military unit components and upgrades.',
    defineFile: 'UnitComponents.json',
    priority: 9,
  },
  {
    slug: 'culture-traits',
    label: 'Culture Trait',
    pluralLabel: 'Culture Traits',
    description: 'Cultural traits that shape your civilization.',
    defineFile: 'CultureTraits.json',
    priority: 10,
  },
  {
    slug: 'character-traits',
    label: 'Character Trait',
    pluralLabel: 'Character Traits',
    description: 'Personality and skill traits for characters.',
    defineFile: 'CharacterTraits.json',
    priority: 11,
  },
  {
    slug: 'character-jobs',
    label: 'Character Job',
    pluralLabel: 'Character Jobs',
    description: 'Government roles and character positions.',
    defineFile: 'CharacterJobs.json',
    priority: 12,
  },
  {
    slug: 'events',
    label: 'Event',
    pluralLabel: 'Events',
    description: 'Narrative and gameplay events.',
    defineFile: 'Events.json',
    priority: 13,
  },
  {
    slug: 'situations',
    label: 'Situation',
    pluralLabel: 'Situations',
    description: 'Ongoing situations and crises.',
    defineFile: 'Situations.json',
    priority: 14,
  },
  {
    slug: 'eras',
    label: 'Era',
    pluralLabel: 'Eras',
    description: 'Historical and future eras.',
    defineFile: 'Eras.json',
    priority: 15,
  },
  {
    slug: 'deposits',
    label: 'Deposit',
    pluralLabel: 'Deposits',
    description: 'Regional deposits and special sites.',
    defineFile: 'Deposits.json',
    priority: 16,
  },
  {
    slug: 'deposit-resources',
    label: 'Deposit Resource',
    pluralLabel: 'Deposit Resources',
    description: 'Resources extracted from deposits.',
    defineFile: 'DepositResources.json',
    priority: 17,
  },
  {
    slug: 'static-modifiers',
    label: 'Static Modifier',
    pluralLabel: 'Static Modifiers',
    description: 'Bundled static modifier packages.',
    defineFile: 'StaticModifiers.json',
    priority: 18,
  },
  {
    slug: 'mission-components',
    label: 'Mission Component',
    pluralLabel: 'Mission Components',
    description: 'Diplomatic mission components.',
    priority: 19,
  },
];

export const CATEGORY_BY_SLUG = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c]),
);

export const DEFINE_FILE_TO_SLUG: Record<string, string> = Object.fromEntries(
  CATEGORIES.filter((c) => c.defineFile).map((c) => [c.defineFile!, c.slug]),
);
